AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: AWS Serverless Specification for pdf generation service.
Resources:
  PdfService:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: src/handlers/getPdfBuffer.handler
      Runtime: nodejs16.x
      FunctionName: Pdf-Service
      CodeUri: .
      Description: "Lambda for generating pdfs"
      MemorySize: 2048
      Timeout: 900
      Layers:
      - Ref: NodeModulesLayer
  NodeModulesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: pdf-service-node-modules
      Description: Dependencies for pdf service.
      Content: src/node_modules_layer
      CompatibleRuntimes:
        - nodejs16.x
