version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pdf-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xsysu2pmpujm"
s3_prefix = "pdf-service"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
